name: book_events
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  flutter_native_splash: ^2.4.6
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/images/splash_light.png"
  image_dark: "assets/images/splash_dark.png"
  android_gravity: fill
  ios_content_mode: scaleToFill
  fullscreen: true
  android_12:
    image: assets/images/splash_light.png
    image_dark: assets/images/splash_dark.png
    color: "#ffffff"
    color_dark: "#000000"

